- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
        - name: Build an image and push it to a private repo
          community.docker.docker_image:
              build:
                  path: "/opt/jenagenthome/workspace/package_Docker_V3/"
              name: docker.io/vasavitavisala/abctechnologies
              #tag: test
              push: true
              source: build
          register: out
        - debug:
              var: out
        - name: start a container
          community.docker.docker_container:
             name: abc-application
             image: vasavitavisala/abctechnologies
             state: started
             ports:
                 - 1234:8080
             #restart: true
          register: out
        - debug:
              var: out
             #- name: Deploying to kubernetes
        - name: Create a Deployment by reading the definition from a local file
          command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /opt/jenagenthome/workspace/package_Docker_V3/deployment.yml"
          register: out
        - debug:
              var: out


