---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project1
  labels:
    app: devops-project1  # Label applied to deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project1  # Pods will have this label
  template:
    metadata:
      labels:
        app: devops-project1  # Pods inherit this label
    spec:
      containers:
      - name: devops-project1
        image: clara100/abcapp:latest
        ports:
        - containerPort: 8081  # Match the exposed port

---
apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app: devops-project1  # This must match the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 32569
  type: NodePort
